"""Blender mesh -> CT collision asset (single self-contained .collision.c file).

Coordinate convention:
    Blender (X, Y, Z, Z-up, RH)  ->  CT (X, Z, -Y, Y-up, RH)

Output is a single `<name>.collision.c` containing four decls:
    Vec3f          <name>_colVerts[N]
    Vec3w          <name>_colTris[M]
    Rect3D         <name>_boundBox
    ModelCollision <name>_collision
"""

from pathlib import Path


def blender_to_ct(co) -> tuple[float, float, float]:
    """Apply axis swap. `co` is a Blender Vector or 3-tuple."""
    return (co[0], co[2], -co[1])


def _write_collision_c(verts, tris, name: str, out_path: Path) -> dict:
    if not verts or not tris:
        raise ValueError(f"collision asset {name!r} has no triangles")

    xs = [v[0] for v in verts]
    ys = [v[1] for v in verts]
    zs = [v[2] for v in verts]
    bbox_min = (min(xs), min(ys), min(zs))
    bbox_max = (max(xs), max(ys), max(zs))

    out: list[str] = [
        f"/* generated by tools/LevelEditor/blender : collision asset for {name} */\n",
        '#include "common.h"\n',
        '#include "common_structs.h"\n\n',
        f"Vec3f {name}_colVerts[{len(verts)}] = {{\n",
    ]
    out += [f"    {{{x:.4f}f, {y:.4f}f, {z:.4f}f}},\n" for (x, y, z) in verts]
    out.append("};\n\n")

    out.append(f"Vec3w {name}_colTris[{len(tris)}] = {{\n")
    out += [f"    {{{a}, {b}, {c}}},\n" for (a, b, c) in tris]
    out.append("};\n\n")

    out.append(
        f"Rect3D {name}_boundBox = {{\n"
        f"    {{{bbox_min[0]:.4f}f, {bbox_min[1]:.4f}f, {bbox_min[2]:.4f}f}},\n"
        f"    {{{bbox_max[0]:.4f}f, {bbox_max[1]:.4f}f, {bbox_max[2]:.4f}f}},\n"
        f"}};\n\n"
    )

    out.append(
        f"ModelCollision {name}_collision = {{\n"
        f"    {len(verts)}, {len(tris)},\n"
        f"    {name}_colVerts, {name}_colTris, &{name}_boundBox,\n"
        f"}};\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(out))

    return {"verts": len(verts), "tris": len(tris), "path": str(out_path)}


def emit_collision(mesh_obj, name: str, out_path: Path) -> dict:
    """Triangulate the mesh, apply world transform, and write a .collision.c."""
    mesh = mesh_obj.data
    mesh.calc_loop_triangles()
    mat = mesh_obj.matrix_world
    verts = [blender_to_ct((mat @ v.co)) for v in mesh.vertices]
    tris = [(t.vertices[0], t.vertices[1], t.vertices[2]) for t in mesh.loop_triangles]
    return _write_collision_c(verts, tris, name, out_path)


def emit_collision_modelspace(mesh_obj, name: str, out_path: Path) -> dict:
    """Like emit_collision but exports in model-local space (no world transform)."""
    mesh = mesh_obj.data
    mesh.calc_loop_triangles()
    verts = [blender_to_ct(v.co) for v in mesh.vertices]
    tris = [(t.vertices[0], t.vertices[1], t.vertices[2]) for t in mesh.loop_triangles]
    return _write_collision_c(verts, tris, name, out_path)
